# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f49bf98886963773e14eb589ab56602837b65f53e48c62027d42ca5780f6ea65dcc8dedde65b17b65588aa1ede76a0b97a07ecad45401b9667a4effdad37ad8

test:
  secret_key_base: e373c2d14487cabe991cc7a5772698652508cc564dc712b01aefed4f8ea467f4acd967c84513a101b2060e115f1fc9f76a51e6ff94c1780d92cc1f18acef57ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
